[workspace]
members = [
    "packages/*",
    "contracts/assembly",
    "contracts/builder_unlock",
    "contracts/escrow_fee_distributor",
    "contracts/voting_escrow",
    "contracts/generator_controller",
]

[patch."https://github.com/astroport-fi/astroport-governance.git"]
astroport-governance = { path = "packages/astroport-governance" }

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
