[workspace]
members = ["packages/*", "contracts/*"]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
astroport = { version = "2.8", git = "https://github.com/astroport-fi/astroport-core", tag = "v2.8.0" }