[workspace]
members = [
    "packages/*",
    "contracts/*",
]

[patch."https://github.com/astroport-fi/hidden_astroport_governance.git"]
astroport-governance = { path = "packages/astroport-governance" }

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
