[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/assembly",
    "contracts/builder_unlock",
    "contracts/generator_controller_lite",
    "contracts/hub",
    "contracts/outpost",
    "contracts/voting_escrow_lite",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[patch.'https://github.com/astroport-fi/hidden_astroport_governance']
astroport-governance = { path = "packages/astroport-governance" }
