[package]
name = "astro-assembly"
version = "1.2.1"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
testnet = ["astroport-governance/testnet"]
library = []

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = { version = "1.1", features = ["ibc3"] }
cw-storage-plus = "0.15"
astroport-governance = { path = "../../packages/astroport-governance" }
ibc-controller-package = { git = "https://github.com/astroport-fi/astroport_ibc.git", branch = "release" }
astroport = { git = "https://github.com/astroport-fi/hidden_astroport_core.git", branch = "release" }
thiserror = { version = "1.0" }
cosmwasm-schema = "1.1"

[dev-dependencies]
cw-multi-test = "0.15"

astroport-token = { git = "https://github.com/astroport-fi/hidden_astroport_core.git", branch = "release" }
astroport-xastro-token = { git = "https://github.com/astroport-fi/hidden_astroport_core.git", branch = "release" }
voting-escrow = { path = "../voting_escrow", default-features = false }
astroport-staking = { git = "https://github.com/astroport-fi/hidden_astroport_core.git", branch = "release" }
builder-unlock = { path = "../builder_unlock", default-features = false }
anyhow = "1"
