[package]
name = "astro-assembly"
version = "1.2.0"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cw2 = "0.13"
cw20 = "0.13"
cosmwasm-std = "1.0"
cw-storage-plus = "0.13"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport-governance = { path = "../../packages/astroport-governance" }
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = "1.0"
cw-multi-test = "0.13"
astroport-token = {git = "https://github.com/astroport-fi/astroport.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
astroport-xastro-token = {git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0"}
voting-escrow = { path= "../voting_escrow" }
astroport-staking = {git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/update_main_to_cosmwasm_1.0.0" }
builder-unlock = {path = "../builder_unlock" }
anyhow = "1"
