[package]
name = "astro-assembly"
version = "2.0.0"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
testnet = []
library = []

[dependencies]
cw2 = "1"
cosmwasm-std = { version = "1.5", features = ["ibc3", "cosmwasm_1_1"] }
cw-storage-plus = "1.2.0"
astroport-governance = { path = "../../packages/astroport-governance" }
astroport = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/neutron-migration" }
ibc-controller-package = "1.0.0"
thiserror = "1"
cosmwasm-schema = "1.5"
cw-utils = "1"

[dev-dependencies]
cw-multi-test = { git = "https://github.com/astroport-fi/cw-multi-test", branch = "feat/bank_with_send_hooks", features = ["cosmwasm_1_1"] }
osmosis-std = "0.21"
astroport-hub = { path = "../hub" }
voting-escrow-lite = { path = "../voting_escrow_lite" }
voting-escrow-delegation = { path = "../voting_escrow_delegation" }
astroport-nft = { path = "../nft" }
astroport-staking = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/neutron-migration" }
astroport-tokenfactory-tracker = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/neutron-migration" }
builder-unlock = { path = "../builder_unlock" }
anyhow = "1"
test-case = "3.3.1"