[package]
name = "astro-assembly"
version = "1.0.0"
authors = ["Astroport"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cw2 = { version = "0.8" }
cw20 = { version = "0.8" }
cosmwasm-std = { version = "0.16.0" }
cw-storage-plus = {version = "0.8.0", features = ['iterator']}
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport-governance = { path = "../../packages/astroport-governance", default-features = false, version = "1.0.0"}
astroport = {git = "https://github.com/astroport-fi/astroport.git", package = "astroport"}
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0", default-features = false }
terra-multi-test = {git = "https://github.com/astroport-fi/terra-plus.git", tag = "v0.9.1-terra"}
astroport-token = {git = "https://github.com/astroport-fi/astroport.git", package = "astroport-token"}
astroport-xastro-token = {git = "https://github.com/astroport-fi/astroport.git",package = "astroport-xastro-token"}
astroport-staking = {git = "https://github.com/astroport-fi/astroport.git", package = "astroport-staking"}
builder-unlock = {path = "../builder_unlock", default-features = false, version = "1.0.0"}
anyhow = "1"
