[package]
name = "astro-assembly"
version = "1.1.1"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cw2 = "0.13.3"
cw20 = "0.13.3"
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.3"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport-governance = { path = "../../packages/astroport-governance", default-features = false, version = "1.0.0"}
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
cw-multi-test = "0.13.2"
astroport-token = {git = "https://github.com/astroport-fi/astroport.git", branch = "release/terra2" }
astroport-xastro-token = {git = "https://github.com/astroport-fi/astroport-core.git", branch = "main"}
voting-escrow = { path= "../voting_escrow", default-features = false, version = "1.0.0" }
astroport-staking = {git = "https://github.com/astroport-fi/astroport-core.git", branch = "main" }
builder-unlock = {path = "../builder_unlock", default-features = false, version = "1.0.0"}
anyhow = "1"
