[package]
name = "astro-assembly"
version = "1.5.0"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
testnet = ["astroport-governance/testnet"]
library = []

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = { version = "1.1", features = ["ibc3"] }
cw-storage-plus = "0.15"
astroport-governance = { path = "../../packages/astroport-governance" }
ibc-controller-package = { git = "https://github.com/astroport-fi/astroport_ibc", branch = "main" }
thiserror = { version = "1.0" }
cosmwasm-schema = "1.1"

[dev-dependencies]
cw-multi-test = "0.15"
astroport-token = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-xastro-token = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
voting-escrow = { path = "../voting_escrow" }
voting-escrow-delegation = { path = "../voting_escrow_delegation" }
astroport-nft = { path = "../nft" }
astroport-staking = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
builder-unlock = { path = "../builder_unlock" }
anyhow = "1"
