[package]
name = "astroport-assembly"
version = "1.3.1"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = "1.1"
cw-storage-plus = "0.15"
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
astroport-governance = { path = "../../packages/astroport_governance" }
ap-xastro-token = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
ap-assembly = { path = "../../packages/assembly" }
ap-builder-unlock = { path = "../../packages/builder_unlock" }
ap-voting-escrow = { path = "../../packages/voting_escrow" }
ap-voting-escrow-delegation = { path = "../../packages/voting_escrow_delegation" }
thiserror = { version = "1.0" }
cosmwasm-schema = "1.1"

[dev-dependencies]
cw-multi-test = "0.15"
astroport-token = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
astroport-xastro-token = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
astroport-voting-escrow = { path = "../voting_escrow" }
astroport-voting-escrow-delegation = { path = "../voting_escrow_delegation" }
astroport-nft = { path = "../nft" }
ap-staking = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
astroport-staking = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
astroport-builder-unlock = { path = "../builder_unlock" }
ap-token = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "feat/separate_astroport_package" }
anyhow = "1"
