[package]
name = "astroport-tests-lite"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = "1.1"

cosmwasm-schema = "1.1"
cw-multi-test = "0.16"
astroport = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }

astroport-escrow-fee-distributor = { path = "../../contracts/escrow_fee_distributor" }
astroport-governance = { path = "../astroport-governance" }
voting-escrow-lite = { path = "../../contracts/voting_escrow_lite" }
generator-controller-lite = { path = "../../contracts/generator_controller_lite" }
astro-assembly = { path = "../../contracts/assembly" }
astroport-generator = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-pair = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-factory = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-token = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-staking = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
astroport-whitelist = { git = "https://github.com/astroport-fi/hidden_astroport_core", branch = "feat/merge_public_20230519" }
anyhow = "1"
